name: Build & Publish Docker Image
on:
  release:
    types: [published]
  
jobs:
  push-to-dockerhub-and-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: shumin12  # secrets.DOCKER_USERNAME
          password: user123123   # secrets.DOCKER_PASSWORD
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: | 
            shumin12/chatbot-ui
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            NEXT_PUBLIC_API_ENDPOINT=https://snapgpt.labs.snaplogicdev.com/api/1/rest/slsched/feed/snaplogic/csirachairat/shared/SnapChain%20Retriever%20Pipeline%20-%20Movies%20Task
            NEXT_PUBLIC_BEARER_TOKEN=aZ6sa9ZQJ7dtO1nznJbzBlZ51QGpsINb
          